# This config is for a large set of stylistic rules useful for lint highlighting.
# This ruleset is not used in CI as it would be too strict.

extends: airbnb
root: true
rules:
  global-require: 0
  no-console: 0
  import/no-extraneous-dependencies: 0
  no-underscore-dangle: 0
